spring:
  application:
    name: cart-service
  redis:
    host: 81.69.200.230
    password: rl18702327006
eureka:
  client:
    service-url:
      defaultZone: http://121.196.169.60:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 81.69.200.230
server:
  port: 8095
raorao:
  jwt:
    pubKeyPath: /home/key/rsa.pub # 公钥地址
    cookieName: RaoRao_TOKEN #名称


